### ISSUE TITLE
Not working with apache poi 5.0.0

### ISSUE THREAD

**Issue by DirkvanWijk** [monitorjbl/excel-streaming-reader#227]
I am using both apache poi (for Excel creation) and this project (for reading large Excels). I have upgraded apache poi to the latest version, which is 5.0.0.

When for example obtaining a row iterator: `sheet.rowIterator()`
I get the following stacktrace:
`java.lang.NoSuchMethodError: org.apache.poi.xssf.model.SharedStringsTable.getEntryAt(I)Lorg/openxmlformats/schemas/spreadsheetml/x2006/main/CTRst;

	at com.monitorjbl.xlsx.impl.StreamingSheetReader.unformattedContents(StreamingSheetReader.java:363)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.handleEvent(StreamingSheetReader.java:200)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.getRow(StreamingSheetReader.java:71)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.access$200(StreamingSheetReader.java:32)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.hasNext(StreamingSheetReader.java:402)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.<init>(StreamingSheetReader.java:396)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.iterator(StreamingSheetReader.java:382)
	at com.monitorjbl.xlsx.impl.StreamingSheet.rowIterator(StreamingSheet.java:57)`

getEntryAt() is deprecated, and most likely removed by now:
https://poi.apache.org/apidocs/dev/org/apache/poi/xssf/model/SharedStringsTable.html

When can we expect this library to upgrade to apache poi 5.0.0? As I cannot upgrade because of this issue.

**Comment by trueg** [comment]
See https://github.com/monitorjbl/excel-streaming-reader/issues/212#issuecomment-618936390

**Comment by monitorjbl** [comment]
The next version of this library will use POI 5.0.0

**Comment by boatrainlsz** [comment]
> The next version of this library will use POI 5.0.0

when the next version will be released? looking forward to it

**Comment by lazydata** [comment]
Looking forward for the next version.

**Comment by aleksandrserbin** [comment]
@monitorjbl is there any help required with the release? It looks like community has a big demand for it 🙂

**Comment by spyro2000** [comment]
Argh, and I am trying to find out why almost EVERYTHING throws an UnsupportedOperationException or NoSuchMethodException on my side, another 3 monthts later :D

**Comment by pjfanning** [comment]
https://github.com/pjfanning/excel-streaming-reader/ uses the latest POI release - if that helps anyone

**Comment by jieyugithub** [comment]
> https://github.com/pjfanning/excel-streaming-reader/ uses the latest POI release - if that helps anyone

It works, thanks very much.
