### PR TITLE
Bump poi from 5.0.0 to 5.2.3

### LINKED ISSUE #227: Not working with apache poi 5.0.0
I am using both apache poi (for Excel creation) and this project (for reading large Excels). I have upgraded apache poi to the latest version, which is 5.0.0.

When for example obtaining a row iterator: `sheet.rowIterator()`
I get the following stacktrace:
`java.lang.NoSuchMethodError: org.apache.poi.xssf.model.SharedStringsTable.getEntryAt(I)Lorg/openxmlformats/schemas/spreadsheetml/x2006/main/CTRst;

	at com.monitorjbl.xlsx.impl.StreamingSheetReader.unformattedContents(StreamingSheetReader.java:363)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.handleEvent(StreamingSheetReader.java:200)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.getRow(StreamingSheetReader.java:71)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.access$200(StreamingSheetReader.java:32)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.hasNext(StreamingSheetReader.java:402)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.<init>(StreamingSheetReader.java:396)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.iterator(StreamingSheetReader.java:382)
	at com.monitorjbl.xlsx.impl.StreamingSheet.rowIterator(StreamingSheet.java:57)`

getEntryAt() is deprecated, and most likely removed by now:
https://poi.apache.org/apidocs/dev/org/apache/poi/xssf/model/SharedStringsTable.html

When can we expect this library to upgrade to apache poi 5.0.0? As I cannot upgrade because of this issue.

### PR DESCRIPTION
**Pull request by peshrus**
Fixes #227

### CODE REVIEW

File: pom.xml [hunk 1]
```diff
@@ -12,8 +12,9 @@
 
   <properties>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
-    <apache.poi.version>5.0.0</apache.poi.version>
+    <apache.poi.version>5.2.3</apache.poi.version>
     <slf4j.version>1.7.30</slf4j.version>
+    <log4j.version>2.18.0</log4j.version>
```
Comment (peshrus) [inline pom.xml:17]: The new version of POI uses this version of log4j

File: pom.xml [hunk 2]
```diff
@@ -140,15 +141,15 @@
     </dependency>
 
     <dependency>
-      <groupId>org.slf4j</groupId>
-      <artifactId>slf4j-log4j12</artifactId>
-      <version>${slf4j.version}</version>
+      <groupId>org.apache.logging.log4j</groupId>
+      <artifactId>log4j-slf4j-impl</artifactId>
```
Comment (peshrus) [inline pom.xml:145]: See https://logging.apache.org/log4j/2.x/log4j-slf4j-impl.html

File: src/main/java/com/monitorjbl/xlsx/impl/StreamingWorkbook.java [hunk 3]
```diff
@@ -509,4 +510,14 @@ public int addOlePackage(byte[] bytes, String s, String s1, String s2) throws IO
...
+
+  @Override
+  public CellReferenceType getCellReferenceType() {
+    throw new UnsupportedOperationException();
+  }
+
+  @Override
+  public void setCellReferenceType(CellReferenceType cellReferenceType) {
+    throw new UnsupportedOperationException();
+  }
```
Comment (peshrus) [inline src/main/java/com/monitorjbl/xlsx/impl/StreamingWorkbook.java:522]: I'm not sure whether it's the proper approach
